version: "3.4"

services:
  magicthegriddening:
    name: mtg-ui
    image: magicthegriddening
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000

  postgres:
    name: mtg-db
    image: postgres:14-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=griddening

  puzzle-seeder:
    name: mtg-seeder
    image: ghcr.io/otherwisejunk/grid-the-seedening:main
    environment:
      - TZ=$TZ
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/griddening?schema=public

  bsky-poster:
    name: mtg-poster
    image: ghcr.io/otherwisejunk/griddening-bsky-bot:main
    environment:
      - TZ=$TZ
      - NODE_ENV=production
      - BLUESKY_USERNAME=$BLUESKY_USERNAME
      - BLUESKY_PASSWORD=$BLUESKY_PASSWORD

  logging:
    name: mtg-logger
    image: griddeninglogger
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/griddening?schema=public
    restart: on-failure

volumes:
  postgres-volume:
