version: '3.4'

services:
  magicthegriddening:
    image: magicthegriddening
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=griddening
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]

volumes:
  postgres-data-volume: