version: '3.4'

services:
  magicthegriddening:
    image: magicthegriddening
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=griddening

volumes:
  postgres-volume: