name: Bsky Bot CI

on:
  push:
    branches: ["main"]
    paths:
      - "apps/bsky-bot/**"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/bsky-bot/**"

defaults:
  run:
    working-directory: apps/bsky-bot

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Use Node.js 24.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24.x
          cache: npm
          cache-dependency-path: apps/bsky-bot/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Format check
        run: npm run fmt:check
      - name: Test
        run: npm test
